#由于九大类报文没有内部类数组的情况，所以length默认为1 innerClassName 默认为空
#使用方法 按顺序 添加数据段信息 只用修改fieldName bits 和 fieldType
message:
  list:
    - fieldList:
        - fieldName: pre
          bits: 24
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: prn
          bits: 6
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: mesType
          bits: 6
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: sow
          bits: 18
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: wn
          bits: 13
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: dif
          bits: 1
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: sif
          bits: 1
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: aif
          bits: 1
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: sisMai
          bits: 4
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: difTwo
          bits: 1
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: sifTwo
          bits: 1
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: aifTwo
          bits: 1
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: iode
          bits: 8
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: ephemeris
          bits: 203
          fieldType: Bit
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: crc
          bits: 24
          fieldType: Bit
      length: 1
      innerClassName: