#由于九大类报文没有内部类数组的情况，所以length默认为1 innerClassName 默认为空
#使用方法 按顺序 添加数据段信息 只用修改fieldName bits 和 fieldType
message:
  list:
    - fieldList:
        - fieldName: pre
          bits: 222
          fieldType: Bit
          notes: pre的报文
      length: 1
      innerClassName:

    - fieldList:
        - fieldName: prn
          bits: 6
          fieldType: Bit
          notes: pre的报文
      length: 1
      innerClassName:

